name = "nhakonta-api"
main = "src/index.ts"
compatibility_date = "2025-06-10"

[build]
command = "pnpm install && pnpm run --filter api build"

# Uncomment and configure the following sections if needed:

[vars]
MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "nhakonta-database"
database_id = "f4807bb4-5070-49d3-909a-8a81a3c9a09e"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

# Uncomment if using Node.js compatibility
# compatibility_flags = ["nodejs_compat"]
